config/routes.rb
get 'oauth_google', :to => 'redmine_oauth#oauth_google'
get 'oauth2callback', :to => 'redmine_oauth#oauth_google_callback', :as => 'oauth_google_callback'

app/controllers/redmine_oauth_controller.rb
require 'json'

class RedmineOauthController < AccountController
  include Helpers::MailHelper
  include Helpers::Checker
  def oauth_google
    if Setting.plugin_redmine_omniauth_google[:oauth_authentification]
      session[:back_url] = params[:back_url]
      redirect_to oauth_client.auth_code.authorize_url(:redirect_uri => oauth_google_callback_url, :scope => scopes)
    else
      password_authentication
    end
  end

  def oauth_google_callback
    if params[:error]
      flash[:error] = l(:notice_access_denied)
      redirect_to signin_path
    else
      token = oauth_client.auth_code.get_token(params[:code], :redirect_uri => oauth_google_callback_url)
      result = token.get('https://www.googleapis.com/oauth2/v1/userinfo')
      info = JSON.parse(result.body)
      if info && info["verified_email"]
        if allowed_domain_for?(info["email"])
          try_to_login info
        else
          flash[:error] = l(:notice_domain_not_allowed, :domain => parse_email(info["email"])[:domain])
          redirect_to signin_path
        end
      else
        flash[:error] = l(:notice_unable_to_obtain_google_credentials)
        redirect_to signin_path
      end
    end
  end

  def try_to_login info
   params[:back_url] = session[:back_url]
   session.delete(:back_url)
   user = User.joins(:email_addresses).where(:email_addresses => { :address => info["email"] }).first_or_create
    if user.new_record?
      # Self-registration off
      redirect_to(home_url) && return unless Setting.self_registration?
      # Create on the fly
      user.firstname, user.lastname = info["name"].split(' ') unless info['name'].nil?
      user.firstname ||= info[:given_name]
      user.lastname ||= info[:family_name]
      user.mail = info["email"]
      user.login = parse_email(info["email"])[:login]
      user.login ||= [user.firstname, user.lastname]*"."
      user.random_password
      user.register

      case Setting.self_registration
      when '1'
        register_by_email_activation(user) do
          onthefly_creation_failed(user)
        end
      when '3'
        register_automatically(user) do
          onthefly_creation_failed(user)
        end
      else
        register_manually_by_administrator(user) do
          onthefly_creation_failed(user)
        end
      end
    else
      # Existing record
      if user.active?
        successful_authentication(user)
      else
        # Redmine 2.4 adds an argument to account_pending
        if Redmine::VERSION::MAJOR > 2 or
          (Redmine::VERSION::MAJOR == 2 and Redmine::VERSION::MINOR >= 4)
          account_pending(user)
        else
          account_pending
        end
      end
    end
  end

  def oauth_client
    @client ||= OAuth2::Client.new(settings[:client_id], settings[:client_secret],
      :site => 'https://accounts.google.com',
      :authorize_url => '/o/oauth2/auth',
      :token_url => '/o/oauth2/token')
  end

  def settings
    @settings ||= Setting.plugin_redmine_omniauth_google
  end

  def scopes
    'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile'
  end
end

app/helpers/redmine_omniauth_helper.rb
module RedmineOmniauthHelper
end

app/views/hooks/_view_account_login_bottom.html.erb
<%= stylesheet_link_tag 'buttons', :plugin => 'redmine_omniauth_google' %>

<% if Setting.plugin_redmine_omniauth_google[:oauth_authentification] %>
 <%= content_tag :div, :class => 'container-link-google' do %>
      <%= link_to oauth_google_path(:back_url => back_url) do %>
        <%= button_tag :class => 'button-login' do %>
            <span class="icon"></span>
            <%= content_tag :span, l(:login_via_google), :class => 'button-text' %>
        <% end %>
      <% end %>
  <% end %>
<% end %>

app/views/settings/_google_settings.html.erb
<p>
  <label><%= l(:client_id) %></label>
  <%= text_field_tag 'settings[client_id]', @settings[:client_id] %>
</p>
<p>
  <label><%= l(:client_secret) %></label>
  <%= text_field_tag 'settings[client_secret]', @settings[:client_secret] %>
</p>
<p>
  <label><%= l(:available_domains) %></label>
  <%= text_area_tag "settings[allowed_domains]", @settings[:allowed_domains], :rows => 5 %>
</p>
<p>
  <label><%= l(:oauth_authentification) %></label>
  <%= check_box_tag "settings[oauth_authentification]", true, @settings[:oauth_authentification] %>
</p>